apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-sriov-cni-ds-installer
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: sriov-cni-ds
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: install-cni
        image: test1
        imagePullPolicy: IfNotPresent
        command:
        - cp
        args:
        - -f
        - /bin/sriov
        - /tmp/sriov-done
        volumeMounts:
        - name: host-cni-etc
          mountPath: /host-cni-etc
        - name: host-cni-bin
          mountPath: /host-cni-bin
      containers:      
      - name: install-cni-sleep
        image: test1
        imagePullPolicy: IfNotPresent
        command: [ "sleep", "1000" ]
      volumes:
      - name: cni
        hostPath:
              path: /etc/cni/net.d/
      - name: host-cni-bin
        hostPath:
              path: /opt/cni/bin
